services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - redis
    depends_on:
      - redis
    entrypoint: ["/bin/sh", "-c", "./scripts/init_tasks.sh & go run main.go"]
    volumes:
      - ./scripts/init_tasks.sh:/init_tasks.sh

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes: [] # Ensure no data volume is mounted
